// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lhoodcpp
double lhoodcpp(SEXP eta, SEXP beta, SEXP doc_ct, SEXP mu, SEXP siginv);
RcppExport SEXP stm_lhoodcpp(SEXP etaSEXP, SEXP betaSEXP, SEXP doc_ctSEXP, SEXP muSEXP, SEXP siginvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type eta(etaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type doc_ct(doc_ctSEXP );
        Rcpp::traits::input_parameter< SEXP >::type mu(muSEXP );
        Rcpp::traits::input_parameter< SEXP >::type siginv(siginvSEXP );
        double __result = lhoodcpp(eta, beta, doc_ct, mu, siginv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gradcpp
arma::vec gradcpp(SEXP eta, SEXP beta, SEXP doc_ct, SEXP mu, SEXP siginv);
RcppExport SEXP stm_gradcpp(SEXP etaSEXP, SEXP betaSEXP, SEXP doc_ctSEXP, SEXP muSEXP, SEXP siginvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type eta(etaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type doc_ct(doc_ctSEXP );
        Rcpp::traits::input_parameter< SEXP >::type mu(muSEXP );
        Rcpp::traits::input_parameter< SEXP >::type siginv(siginvSEXP );
        arma::vec __result = gradcpp(eta, beta, doc_ct, mu, siginv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
